# Exam Practics:-
/*
CREATE SCHEMA EXAM_PRE;

USE EXAM_PRE;

CREATE TABLE EXAM_DATA
(EMP_ID INT NOT NULL,
EMP_NAME VARCHAR(60) NOT NULL,
DEPT VARCHAR(60) NOT NULL,
SALARY INT NOT NULL);
*/
/*
INSERT INTO EXAM_DATA VALUES
(101, "Andrew", "HR", 25000),
(102, "Roger", "IT", 35000),
(103, "Kevin", "HR", 42000),
(104, "Willson", "IT", 23000);
*/

# SELECT * FROM EXAM_DATA;

#ALTER TABLE EXAM_DATA MODIFY COLUMN COUNTRY VARCHAR (60) NOT NULL; 
/*
UPDATE EXAM_DATA
SET COUNTRY = "Brazil"
WHERE EMP_ID = 104;
*/

#DELETE FROM EXAM_DATA
#WHERE COUNTRY = "England";

#ALTER TABLE EXAM_DATA DROP COLUMN COUNTRY;